# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
{...}: {
  imports = [./hardware-configuration.nix];

  boot = {
    loader = {
      grub = {
        enable = true;
        device = "/dev/nvme0n1";
        useOSProber = true;
      };
    };
  };
}
