device_name = "SteelSeries SteelSeries Apex 5"
phys = "usb-0000:00:14.0-8/input0"

# Configure CAPSLOCK as a Dual Role key.
# Holding it produces LEFTCTRL, but tapping it will produce ESC.
[[dual_role]]
input = "KEY_LEFTCTRL"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]
